# Generated by Django 4.2.5 on 2024-09-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0002_alter_productimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
