# Generated by Django 4.2.5 on 2024-09-14 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0004_alter_product_description_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="ec.product",
            ),
        ),
    ]
