# Generated by Django 4.2.5 on 2024-10-03 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0006_cart_cartproduct"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20, verbose_name="名前")),
                ("last_name", models.CharField(max_length=20, verbose_name="名字")),
                (
                    "user_name",
                    models.CharField(max_length=40, verbose_name="ユーザー名"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="メールアドレス"
                    ),
                ),
                ("address1", models.TextField(verbose_name="住所1")),
                ("address2", models.TextField(blank=True, verbose_name="住所2")),
                (
                    "country",
                    models.CharField(
                        default="United States", max_length=20, verbose_name="国"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("CA", "California"),
                            ("TX", "Texas"),
                            ("FL", "Florida"),
                            ("NY", "New York"),
                        ],
                        max_length=20,
                        verbose_name="州",
                    ),
                ),
                ("zip_code", models.CharField(max_length=20, verbose_name="郵便番号")),
                (
                    "card_name",
                    models.CharField(max_length=50, verbose_name="カード名義"),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="カード番号は13桁、15桁、または16桁の数字である必要があります。",
                                regex="^(?:\\d{13}|\\d{15}|\\d{16})$",
                            )
                        ],
                        verbose_name="カード番号",
                    ),
                ),
                (
                    "expiration_date",
                    models.CharField(
                        max_length=5,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="カード有効期限はMM/YY形式である必要があります。",
                                regex="^(0[1-9]|1[0-2])\\/?([0-9]{2})$",
                            )
                        ],
                        verbose_name="カード有効期限",
                    ),
                ),
                (
                    "cvv",
                    models.CharField(
                        max_length=4,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CVVは3桁または4桁の数字である必要があります。",
                                regex="^\\d{3,4}$",
                            )
                        ],
                        verbose_name="セキュリティコード",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="数量",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="購入時の値段")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="ec.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ec.product"
                    ),
                ),
            ],
            options={
                "db_table": "order_detail",
            },
        ),
    ]
