# Generated by Django 4.2.5 on 2024-10-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0007_order_orderdetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(max_length=20, verbose_name="国"),
        ),
    ]
