# Generated by Django 4.2.5 on 2024-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0008_alter_order_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[("", "Choose..."), ("US", "United States")],
                max_length=20,
                verbose_name="国",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("", "Choose..."),
                    ("CA", "California"),
                    ("TX", "Texas"),
                    ("FL", "Florida"),
                    ("NY", "New York"),
                ],
                max_length=20,
                verbose_name="州",
            ),
        ),
    ]
