# Generated by Django 4.2.5 on 2024-10-18 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0009_alter_order_country_alter_order_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromotionCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=7, unique=True, verbose_name="プロモーションコード"
                    ),
                ),
                ("discount_amount", models.PositiveIntegerField(verbose_name="割引額")),
                (
                    "is_applied",
                    models.BooleanField(default=False, verbose_name="適用済みかどうか"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_code",
                        to="ec.order",
                    ),
                ),
            ],
            options={
                "db_table": "promotion_code",
            },
        ),
    ]
