# Generated by Django 4.2.5 on 2024-10-19 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ec", "0010_promotioncode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotioncode",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promotion_code",
                to="ec.order",
            ),
        ),
    ]
